version: '3.8'

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0"]

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0"]

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0"]

  mongo4:
    image: mongo:7
    container_name: mongo4
    ports:
      - 27020:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0"]

networks:
  mongo-cluster:
    driver: bridge
